color0 #03193a
color1 #fd4663
color2 #4e94fd
color3 #4b37fd
color4 #ae37fd
color5 #81b3fe
color6 #8d81fe
color7 #f2f2f3
color8 #5e6672
color9 #fd4663
color10 #4e94fd
color11 #4b37fd
color12 #ae37fd
color13 #81b3fe
color14 #8d81fe
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #03193a
background            #03193a
foreground            #f2f2f3
selection_foreground  #afb2b6
selection_background  #082249
active_border_color   #4e94fd
inactive_border_color #082249
url_color             #4e94fd

active_tab_foreground   #181d25
active_tab_background   #4e94fd
inactive_tab_foreground #afb2b6
inactive_tab_background #082249
cursor_trail_color      #afb2b6
