color0 #291414
color1 #990406
color2 #fa5153
color3 #fa9738
color4 #faf738
color5 #fb8384
color6 #fcbe83
color7 #f3f2f2
color8 #756161
color9 #990406
color10 #fa5153
color11 #fa9738
color12 #faf738
color13 #fb8384
color14 #fcbe83
color15 #f3f2f2

cursor                #f3f2f2
cursor_text_color     #291414
background            #291414
foreground            #f3f2f2
selection_foreground  #b6afaf
selection_background  #371b1b
active_border_color   #fa5153
inactive_border_color #371b1b
url_color             #fa5153

active_tab_foreground   #251819
active_tab_background   #fa5153
inactive_tab_foreground #b6afaf
inactive_tab_background #371b1b
cursor_trail_color      #b6afaf
